### ISSUE TITLE
Blocklist Storage

### ISSUE THREAD

**Issue by msrd0** [LuckyTurtleDev/crab-hole#1]
We need a datastructure that can efficiently store our blocklist and allow domain lookup. That means, for an input domain, we need to know if the domain itself or any domain it is a subdomain of. I see two possibilities:

 - We just use a `HashMap` for the blocklist. Then the lookup needs to split the domain up into all domains it is a subdomain of, and we need (in the worst case) to check for each if it is part of the hash map
 - We use a trie. It appears as if none of the libraries provided on crates.io suffice - the best they have is common prefix, but we need the largest superstring that is actually part of the tree, not any prefix of it. (also, we're running on suffixes, not prefixes)

**Comment by LuckyTurtleDev** [comment]
impl trie solution at 0f2f409c89323f8c1dfeb81d76b12ef63e732ec1
