### ISSUE TITLE
Config validation fails

### ISSUE THREAD

**Issue by NiklasVousten** [LuckyTurtleDev/crab-hole#36]
Due to a recent change, even a correct config will be returned as invalid if the `validate-config` subcommand is used.
This it due to the last commit where an exit code was added to the subcommand, which will return `1` which means failure.

https://github.com/LuckyTurtleDev/crab-hole/blob/72d00cdd1a50d176f550aebae4eeb1d23ed3687d/src/main.rs#L536-L539

`std::process::exit(1);` is not needed.
The program will return with a success on its own afterwards.

**Comment by LuckyTurtleDev** [comment]
ups i mess up
